#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Sat Feb 27 16:55:38 2016
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class FramePrincipal(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FramePrincipal.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.Consultas = wx.StaticText(self, wx.ID_ANY, _("Consultas"))
        self.TextConsulta = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_1 = wx.Button(self, wx.ID_ANY, _(u"A\xf1ade Consulta"))
        self.button_2 = wx.Button(self, wx.ID_ANY, _("Ejecutar Consultas"))
        self.button_3 = wx.Button(self, wx.ID_ANY, _("Destino Consulta"))
        self.DirDestFile = wx.DirDialog(None,"Selecciona el directorio donde se guardaran las consultas...","", wx.DD_DEFAULT_STYLE | wx.DD_DIR_MUST_EXIST)
        self.list_ctrl_1 = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_REPORT | wx.SUNKEN_BORDER)
        self.sizer_2_staticbox = wx.StaticBox(self, wx.ID_ANY, _("AvanzaWoms"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnButtonAddQuery, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.OnButtonExecQuery, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.OnButton_3, self.button_3)
        self.Bind(wx.EVT_LIST_ITEM_RIGHT_CLICK, self.ListSubmenu, self.list_ctrl_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FramePrincipal.__set_properties
        self.SetTitle(_("AvanzaWoms"))
        self.TextConsulta.SetMinSize((200, 28))
        # end wxGlade
        self.list_ctrl_1.InsertColumn(0, "Index")
        self.list_ctrl_1.InsertColumn(1, "Query", format=wx.LIST_FORMAT_CENTER, width=wx.LIST_AUTOSIZE)

    def __do_layout(self):
        # begin wxGlade: FramePrincipal.__do_layout
        self.sizer_2_staticbox.Lower()
        sizer_2 = wx.StaticBoxSizer(self.sizer_2_staticbox, wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(2, 4, 0, 0)
        grid_sizer_1.Add(self.Consultas, 0, 0, 0)
        grid_sizer_1.Add(self.TextConsulta, 0, 0, 0)
        grid_sizer_1.Add(self.button_1, 0, 0, 0)
        grid_sizer_1.Add(self.button_2, 0, 0, 0)
        grid_sizer_1.Add(self.button_3,1,0,0)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_2.Add(self.list_ctrl_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

    def OnButtonAddQuery(self, event):  # wxGlade: FramePrincipal.<event_handler>
        print "Añadir query a lista!"
        Query = self.TextConsulta.GetLineText(0)
        self.list_ctrl_1.Append([str(self.list_ctrl_1.GetItemCount()+1),Query])
        event.Skip()

    def OnButtonExecQuery(self, event):  # wxGlade: FramePrincipal.<event_handler>
        print "Ejecutar Queryes"
        event.Skip()
        
    def ListSubmenu(self, event):
        print "Boton derecho sobre lista"
        event.Skip()
    def OnButton_3(self,event):
        if(self.DirDestFile.ShowModal() == wx.ID_OK):
            self.DirectorioDestino = self.DirDestFile.GetPath()
            print self.DirectorioDestino + "/Outfile.txt"
        else:
            print "Ningun directorio seleccionado"
        event.Skip()

# end of class FramePrincipal
class FramePrin(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_2 = FramePrincipal(None, wx.ID_ANY, "")
        self.SetTopWindow(frame_2)
        frame_2.Show()
        return 1

# end of class FramePrin